### ISSUE TITLE
User Activity for site

### ISSUE THREAD

**Issue by harishp54** [eaxs/User-Activity#7]
Hi
I installed User Activity plug in my joomla web site. it will work for administrator level (i.e) if admin can add any article in back end  then this plug in will display this  activity in my front end site. I want same functionality for normal users (i.e) if user do any activity on my site in front end it should  display on front end site and it will display for all users. will this User-Activity extension support my requirement (or) not. if possible  how can I do that?

**Comment by eaxs** [comment]
Yes that should work. Maybe you forgot to give the "public" group the correct permissions. See here: http://projectfork.net/docs/23-user-activity/46-installation

> Last but not least, you have to configure which groups you want to track, or else the extension won't log anything except for admin activity. To do this, go to:
> 
> Joomla Backend > Components > User Activity > Options
> 
> On the Permissions tab, grant the "Create" permission to the groups you want to track. You don't have to explicitly set this permission for child groups here. Child groups will automatically inherit the permissions from their parents. So if you want to track all groups, give the "Create" permission  to the "Public" group. If you don't want to track admin activity, you'll have to explicitly deny the permission for the Super Users group.

**Comment by harishp54** [comment]
hi eaxs than you   so much for your reply. I will give "Public" group permissions it will only work for administrator it will display like this(Super User wrote an article: sample article 4 1 hour ago). For Normal user it will display any thing. administrator is going to add articles in back end where as normal user do any activity from front end now i want display the same like administrator. 
Is User Activity plug-in will track any 3rd party extensions ,means if my user name some X is going to add an event using some 3rd party extensions like "Icagenda". so i want to display   like this "user X is add an event" and it should visible for all users.

**Comment by harishp54** [comment]
hi eaxs than you so much for your reply. I will give "Public" group permissions it will only work for administrator it will display like this(Super User wrote an article: sample article 4 1 hour ago). For Normal user it will display any thing. administrator is going to add articles in back end where as normal user do any activity from front end now i want display the same like administrator.
Is User Activity plug-in will track any 3rd party extensions ,means if my user name some X is going to add an event using some 3rd party extensions like "Icagenda". so i want to display like this "user X is add an event" and it should visible for all users.

**Comment by eaxs** [comment]
I'm guessing that's because the component/module is configured to show _frontend_ activity, and not _backend_ activity. See here: http://projectfork.net/docs/23-user-activity/50-faq-support

> Q: I don't see any activity in the component or module. What's wrong?
> 
> Double-check the filter settings of the component or module. Activity is always shown from either the backend or the frontend.
> For example, when you create an article in the Joomla backend, and your module is configured to display frontend activity, this record will not be visible.

#

> Is User Activity plug-in will track any 3rd party extensions ,means if my user name some X is going to add an event using some 3rd party extensions like "Icagenda"

Yes it can, but it needs a plugin for that :)

**Comment by harishp54** [comment]
Do you have any idea about plugin please suggest me it will help me to meet my requirement

**Comment by eaxs** [comment]
I'm sorry but I don't know if there is a plugin for this extension. Best to ask the developers of Icagenda ;)
